### ISSUE TITLE
Upgrade Z3 to 4.13.3

### ISSUE THREAD

**Issue by msprotz** [hacl-star/hacl-star#1014]
This is just an issue to discuss upgrading to Z3 4.13.3.

Is this a good idea? I'm not sure.

Pros:
- no more emulation for Apple Silicon (4.8.5 does not work on aarch64)
- consistency with F* -- HACL* is not left behind using an older version of Z3
- elimination of long-standing z3 bugs ("vector overflow, internal error", etc.) 

Cons:
- more work to update proofs, fix things up
- possible performance regressions
- users would have to fix their setups to have the proper symlinks.

Status is as follows:
- I have had a build running for a while, so far, no file has failed outright -- some had to have their rlimits bumped (via z3rlimit_factor, on the command-line), but no dealbreaker at this stage
- however, the build is not finished because some vale files are taking an outrageous amount of time:

```
[VERIFY] Vale.Curve25519.X64.FastSqr.fst, 49:22.94
```

<img width="431" alt="Screenshot 2024-12-26 at 11 03 19 AM" src="https://github.com/user-attachments/assets/5f233b07-9320-4dd2-8b23-26bf717f5d01" />

What would be needed?
- Update nix flake, CI, build, etc.
- Proper checks in the build to make sure users have a proper setup
- Strengthen proofs and debug why Vale is taking so very long

CC @gebner @mtzguido @R1kM

**Comment by msprotz** [comment]
These are the four files that the build is stuck on:

```
Hacl.Spec.BignumQ.Mul
Vale.Curve25519.X64.FastMul
Hacl.Spec.Poly1305.Equiv
Vale.Curve25519.FastSqr_helpers
```

those are currently at 1h+ of Z3 time

**Comment by gebner** [comment]
We plan to switch the default Z3 version to 4.13.3 in the near future.  I would expect that we'll want to drop 4.8.5 from the distribution at some point as well.  That version is over five years old now.

> users would have to fix their setups to have the proper symlinks.

Unless you exclusively work on HACL*, you'll need to do that anyhow.  F* requires 4.13.3, Pulse requires 4.13.3, the number of projects requiring 4.13.3 is only going to increase.

> Update nix flake, CI, build, etc.

The F* nix flake already comes with both z3-4.8.5 and z3-4.13.3.

> Proper checks in the build to make sure users have a proper setup

F* already checks the Z3 version and you get a somewhat reasonable error message if the setup is not configured correctly:
```
* Error 357 at Scratch.fst(8,0-9,22):
  - Unexpected Z3 version for 'z3': expected '4.8.5', got '4.13.3'.
  - Please download version 4.8.5 of Z3 from
        https://github.com/Z3Prover/z3/releases
    and install it into your $PATH as 'z3-4.8.5'.

1 error was reported (see above)
```

**Comment by msprotz** [comment]
Yeah that sounds reasonable, my only qualm is that I don't know how to go about debugging proof obligations that suddenly start taking 40+ minutes -- does the new z3 come with any way to know what's taking so much time? (I can dream: it's Christmas)

**Comment by msprotz** [comment]
But realistically, it would be nice to understand if there's new (non-intuitive) behavior that we need to be aware of for HACL*. As in: "these kinds of things used to work great but now not so much anymore".

**Comment by msprotz** [comment]
Going to write down the failures here:

- after four hours:

```
Failed after: 4:25:13
Full log is in obj/Hacl.Spec.Poly1305.Equiv.fst.checked.{out,err}, see excerpt below:
* Error 19 at /Users/jonathan/Code/everest/hacl-star/code/poly1305/Hacl.Spec.Poly1305.Equiv.fst(183,9-183,56):
  - Assertion failed
  - See also Prims.fst(441,83-441,96)
  ```

**Comment by msprotz** [comment]
@gebner I looked at code/poly1305/Hacl.Spec.Poly1305.Equiv.fst in HACL* and the file has an rlimit of 50 -- why are we seeing failures after 4 hours? do you have any sense of what's happening? this seems like irregular behavior that goes beyond of what one might expect from switching to a different version of z3

**Comment by gebner** [comment]
I think @mtzguido has a lot more experience with the changes in Z3, and with HACL*.

**Comment by R1kM** [comment]
I'm generally favorable about switching to a more recent Z3 for HACL*. However, I believe we first need to reach the point where there is little to no proof performance regression. In particular, I see files now taking 45 minutes to verify as problematic.
If @mtzguido has insights about changes in Z3 that might cause this, and how to debug these proofs, I can dedicate some time in January to work on this.

Regarding fixing local configurations, hopefully Z3 4.13.3 will be easier to install, but it might be useful to include corresponding binaries in the z3-binaries repo to simplify fixing installs.

**Comment by mtzguido** [comment]
We found a few proofs in the F* repo showing similar behaviors. It seemed that there's no clear reason (e.g. changing the random seed makes the problem go away), and that between 4.8.5 and 4.13.3 there was some innocuous change that just changed a default, and affected this behavior. I think it would probably be best if we look at these proofs at the Z3 before trying to work with them in F*. I can also try them locally and see if I can minimize them, and if the random seed also affects these.

I think you could consider using 4.8.5 only for these files until the problem is sorted or at least better understood, and 4.13.3 on the rest. Maybe we can later upgrade to 4.14.4 throughout.

> Regarding fixing local configurations, hopefully Z3 4.13.3 will be easier to install, but it might be useful to include corresponding binaries in the z3-binaries repo to simplify fixing installs.

There is now a script shipped with F* for this purpose, and installs both versions: `./bin/get_fstar_z3.sh`. Running `./everest z3` calls this script too.

**Comment by msprotz** [comment]
My question is: the rlimit puts an upper bound on the "time budget" that z3 has. 50 is a very low rlimit that historically has corresponded to maybe a few minutes, max. I am now seeing files that have an rlimit of 50 fail after six hours, like Hacl.Spec.Poly1305.Equiv.Checked. Why did the meaning of rlimit change?

To me, that is what prevents progress on the migration: if suddenly the rlimit doesn't mean anything anymore, it's going to be very hard to upgrade HACL* to Z3, and it's going to be even harder to maintain those proofs.

Ideally, I would like to understand why rlimit doesn't mean anything anymore in those cases, because I have no recollection of such extreme cases ever happening with the old Z3.

Thanks!

**Comment by msprotz** [comment]
> However, I believe we first need to reach the point where there is little to no proof performance regression. In particular, I see files now taking 45 minutes to verify as problematic.

@R1kM I think gathering data would help us make a case. Like, run a build with 4.8.5, another one with 4.13.3, and see how much the Z3 times have changed -- maybe a histogram of the diff (-1 to 1%, +2% to +5%, etc.)

**Comment by mtzguido** [comment]
> My question is: the rlimit puts an upper bound on the "time budget" that z3 has. 50 is a very low rlimit that historically has corresponded to maybe a few minutes, max. I am now seeing files that have an rlimit of 50 fail after six hours, like Hacl.Spec.Poly1305.Equiv.Checked. Why did the meaning of rlimit change?

Ah yes, good point sorry. This is probably an "rlimit leak": Z3 doing a bunch of work without increasing the rlimit counter. We've found a few of these before and they were fixed. I can try to minimize this one.

**Comment by msprotz** [comment]
@mtzguido did you end up making progress on this one? having to build z3 4.8.5 as part of the CI is becoming more and more painful

maybe the behavior would be different now with context pruning enabled? worth another try?

**Comment by mtzguido** [comment]
I just tried the minimal repro again with the latest Z3 (4.14.1) and it seems to work very fast, so maybe this issue got solved. I'll try a HACL* build with that version.

**Comment by msprotz** [comment]
wonderful, thanks Guido -- very eager to hear about the results

**Comment by mtzguido** [comment]
There are still a few failures.. we could minimize them and report Z3 bugs, but maybe we can just rewrite these proofs a bit. I fixed a couple locally, I will post a PR for that in any case.

**Comment by msprotz** [comment]
Do we still see a time explosion on the previously problematic files?

**Comment by mtzguido** [comment]
The ones currently diverging for me are `Vale.Curve25519.FastSqr_helpers.fst` and `Vale.Curve25519.X64.FastMul.fst`. Both `Hacl.Spec.BignumQ.Mul` and `Hacl.Spec.Poly1305.Equiv` seem to work now.

**Comment by Chris-Hawblitzel** [comment]
I tried just going from Z3 4.8.5 to Z3 4.8.15, and `Vale.Curve25519.FastSqr_helpers.fst` took 6 hours before I stopped it.  It looks like nonlinear arithmetic.

**Comment by msprotz** [comment]
Ok so then we'd have to debug what exactly is the problematic proof. Thanks Chris.

**Comment by R1kM** [comment]
Interestingly, both `Vale.Curve25519.FastSqr_helpers.fst` and `Vale.Curve25519.X64.FastMul.fst` seem to succeed on my Mac when using Z3 4.13.3, starting from a clean build.
@Chris-Hawblitzel do you know which proof is particularly failing in FastSqr_helpers?

**Comment by msprotz** [comment]
@R1kM if you managed to verify those files, do you mind pushing fresh hints to see if that helps?

**Comment by msprotz** [comment]
at this stage I'm tempted to push a build to CI with those hints and see how it behaves (provided CI has a timeout...)

**Comment by mtzguido** [comment]
I pushed a branch `guido_z3_4.14.1` with my state, there are 7 admitted proofs but I think that's it (running a clean build to confirm). @R1kM  if you got a build with 4.13.3 maybe we can compare the failures/admits, and try to minimize and report to upstream.

I'm not sure what a good strategy is for deciding whether to version bump, this kind of stochastic behavior may remain. A possibility is using one default version and switching to others for the flaky proofs as needed.

**Comment by Chris-Hawblitzel** [comment]
> Interestingly, both Vale.Curve25519.FastSqr_helpers.fst and Vale.Curve25519.X64.FastMul.fst seem to succeed on my Mac when using Z3 4.13.3, starting from a clean build.

It also succeeds on my Windows machine with 4.13.3.  It just appears to be very unstable across versions, presumably because it's a proof about nonlinear arithmetic (specifically, squaring).

> @Chris-Hawblitzel do you know which proof is particularly failing in FastSqr_helpers?

There were two lemmas in that file and they both run for a long time.
